server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.8.41.136:3306/lianjia_db
    username: root
    password: 123
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
  http:
    encoding:
      force: true
  data:
          elasticsearch:
              cluster-name: elasticsearch
              node-name: node1
              cluster-nodes: 10.8.41.142:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
mybatis:
  type-aliases-package: com.tedu.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml






